export const HAS_ERROR = 'HAS_ERROR';
export const FETCHING_DATA = 'FETCHING_DATA';
export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEES';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';